version: '3'

services:
  pgsteam:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsteam'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: steam
      POSTGRES_PASSWORD: pgpassword

volumes:
  pg-data: